# This file is autogenerated. Do not change.


module NIAVUGTJPEWIDHFV
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//001.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_001.png", output); 
        save("./tmp/WGLMakie_001.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module FGFVGXGDMLCYLHOK
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//002.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_002.png", output); 
        save("./tmp/WGLMakie_002.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SUWGTGTVHWBFYDHZ
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//003.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_003.png", output); 
        save("./tmp/WGLMakie_003.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MZPUVZIQOELLRCUR
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//004.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_004.png", output); 
        save("./tmp/WGLMakie_004.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module CJUJKFGJEBHOQQYK
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//005.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_005.png", output); 
        save("./tmp/WGLMakie_005.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EDLJCKDBNCCJOFVA
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//006.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_006.png", output); 
        save("./tmp/WGLMakie_006.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LNQQSVXSNILSVGMI
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//007.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_007.png", output); 
        save("./tmp/WGLMakie_007.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RJZYLHVQXYXRDYWD
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//008.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_008.png", output); 
        save("./tmp/WGLMakie_008.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module VWXSLGDFIQUEIGHL
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//009.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_009.png", output); 
        save("./tmp/WGLMakie_009.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ENUHEFAJWXATVBVD
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//010.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_010.png", output); 
        save("./tmp/WGLMakie_010.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QJIBSAKTIGHVBFXX
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//011.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_011.png", output); 
        save("./tmp/WGLMakie_011.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ITMVMZFYJTQKEEFW
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//012.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_012.png", output); 
        save("./tmp/WGLMakie_012.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IBGMEHVAUCVZTAZR
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//013.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_013.png", output); 
        save("./tmp/WGLMakie_013.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module UBWLIGAQVTKWUCYN
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//014.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_014.png", output); 
        save("./tmp/WGLMakie_014.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SARBYLBNVPWSRIKQ
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//015.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_015.png", output); 
        save("./tmp/WGLMakie_015.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module UPJITMQRQPJTAPZR
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//016.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_016.png", output); 
        save("./tmp/WGLMakie_016.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EIFHSMSGQASYPALX
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//017.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_017.png", output); 
        save("./tmp/WGLMakie_017.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module OGYYDBUACJKZAHPK
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//018.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_018.png", output); 
        save("./tmp/WGLMakie_018.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module HNLAWBTWHZBZITIE
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//019.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_019.png", output); 
        save("./tmp/WGLMakie_019.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IBBXZPPRCQWMCIZE
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//020.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_020.png", output); 
        save("./tmp/WGLMakie_020.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QZKRGCQRPHBSGVAM
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//021.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_021.png", output); 
        save("./tmp/WGLMakie_021.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RLAXUOYSPLRHHZOH
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//022.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_022.png", output); 
        save("./tmp/WGLMakie_022.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PHPVWCLALOAVVPDA
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//023.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_023.png", output); 
        save("./tmp/WGLMakie_023.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SUJVBROVFGZTXYZT
    try
        using WGLMakie; WGLMakie.activate!(); 
output = include("./snippets/makie//025.jl")
    display(output);
    try 
        save("./tmp/WGLMakie_025.png", output); 
        save("./tmp/WGLMakie_025.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end





module PXRXWFIXKRSAIIRG
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//001.jl")
    display(output);
    try 
        save("./tmp/GLMakie_001.png", output); 
        save("./tmp/GLMakie_001.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module CCUXDGFAPWKHXDTF
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//002.jl")
    display(output);
    try 
        save("./tmp/GLMakie_002.png", output); 
        save("./tmp/GLMakie_002.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LKQBSXWRDINBPYII
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//003.jl")
    display(output);
    try 
        save("./tmp/GLMakie_003.png", output); 
        save("./tmp/GLMakie_003.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module HPBEDBHIMYFUFFLG
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//004.jl")
    display(output);
    try 
        save("./tmp/GLMakie_004.png", output); 
        save("./tmp/GLMakie_004.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DXDNFLBWEAHIORLU
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//005.jl")
    display(output);
    try 
        save("./tmp/GLMakie_005.png", output); 
        save("./tmp/GLMakie_005.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LJSJQYOKHHNLBLJP
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//006.jl")
    display(output);
    try 
        save("./tmp/GLMakie_006.png", output); 
        save("./tmp/GLMakie_006.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MUIDTLFMOMPDXXUA
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//007.jl")
    display(output);
    try 
        save("./tmp/GLMakie_007.png", output); 
        save("./tmp/GLMakie_007.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SANORYEUTXIJQPOU
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//008.jl")
    display(output);
    try 
        save("./tmp/GLMakie_008.png", output); 
        save("./tmp/GLMakie_008.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IICQVXLDRZMLIPVX
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//009.jl")
    display(output);
    try 
        save("./tmp/GLMakie_009.png", output); 
        save("./tmp/GLMakie_009.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module WJTGGMZHHLNZEDGV
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//010.jl")
    display(output);
    try 
        save("./tmp/GLMakie_010.png", output); 
        save("./tmp/GLMakie_010.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module GXZPUQTXRKGGBETZ
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//011.jl")
    display(output);
    try 
        save("./tmp/GLMakie_011.png", output); 
        save("./tmp/GLMakie_011.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module OKSONAIHXTETOJFO
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//012.jl")
    display(output);
    try 
        save("./tmp/GLMakie_012.png", output); 
        save("./tmp/GLMakie_012.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RUDRHYMTUZRITUFC
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//013.jl")
    display(output);
    try 
        save("./tmp/GLMakie_013.png", output); 
        save("./tmp/GLMakie_013.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MJYEJPTYSRKQRNIR
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//014.jl")
    display(output);
    try 
        save("./tmp/GLMakie_014.png", output); 
        save("./tmp/GLMakie_014.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module BQWHHGAQIAGOCAXX
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//015.jl")
    display(output);
    try 
        save("./tmp/GLMakie_015.png", output); 
        save("./tmp/GLMakie_015.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DIBHLRYLYVOIKZCD
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//016.jl")
    display(output);
    try 
        save("./tmp/GLMakie_016.png", output); 
        save("./tmp/GLMakie_016.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IJXGYBADJYXYQRAB
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//017.jl")
    display(output);
    try 
        save("./tmp/GLMakie_017.png", output); 
        save("./tmp/GLMakie_017.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PGKJWYTZUXDHYXHC
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//018.jl")
    display(output);
    try 
        save("./tmp/GLMakie_018.png", output); 
        save("./tmp/GLMakie_018.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PBMDJUXLEKSZUMFV
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//019.jl")
    display(output);
    try 
        save("./tmp/GLMakie_019.png", output); 
        save("./tmp/GLMakie_019.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LXWCBBZROIPECVIJ
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//020.jl")
    display(output);
    try 
        save("./tmp/GLMakie_020.png", output); 
        save("./tmp/GLMakie_020.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module XUIKKXEHMESJAMBZ
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//021.jl")
    display(output);
    try 
        save("./tmp/GLMakie_021.png", output); 
        save("./tmp/GLMakie_021.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PBKJJNDBSALIVTQM
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//022.jl")
    display(output);
    try 
        save("./tmp/GLMakie_022.png", output); 
        save("./tmp/GLMakie_022.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ZEJVIWAKHEVLWNKJ
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//023.jl")
    display(output);
    try 
        save("./tmp/GLMakie_023.png", output); 
        save("./tmp/GLMakie_023.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module UVKBWTLPOTXVTPNN
    try
        using GLMakie; GLMakie.activate!(); 
output = include("./snippets/makie//025.jl")
    display(output);
    try 
        save("./tmp/GLMakie_025.png", output); 
        save("./tmp/GLMakie_025.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end





module PXJTEZTQMHFTXWIB
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//001.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_001.png", output); 
        save("./tmp/CairoMakie_001.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ROJOJJGMHFYTCKKN
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//002.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_002.png", output); 
        save("./tmp/CairoMakie_002.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module HRTORTTGHMCGLTMD
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//003.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_003.png", output); 
        save("./tmp/CairoMakie_003.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SOPSWHBMKNPCZQPS
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//004.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_004.png", output); 
        save("./tmp/CairoMakie_004.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module GAGJNHKAZRKYZGSL
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//005.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_005.png", output); 
        save("./tmp/CairoMakie_005.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module JITLSEEUWAPLAINR
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//006.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_006.png", output); 
        save("./tmp/CairoMakie_006.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module NUYEDCCEVAGPBUKR
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//007.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_007.png", output); 
        save("./tmp/CairoMakie_007.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EJVJHZSIDNRATDYH
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//008.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_008.png", output); 
        save("./tmp/CairoMakie_008.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QJZFHSSRPYNZCPGM
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//009.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_009.png", output); 
        save("./tmp/CairoMakie_009.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EPCDMVQEREFDSPBQ
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//010.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_010.png", output); 
        save("./tmp/CairoMakie_010.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module YVQSWZSGEHUPNZHW
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//011.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_011.png", output); 
        save("./tmp/CairoMakie_011.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module NIZLJHICSKXIVCDA
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//012.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_012.png", output); 
        save("./tmp/CairoMakie_012.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module GHCZERZJDGYLKHFH
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//013.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_013.png", output); 
        save("./tmp/CairoMakie_013.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module GHBUHXQDDQVUUBJS
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//014.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_014.png", output); 
        save("./tmp/CairoMakie_014.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RFCNCZGTPPNBWOQM
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//015.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_015.png", output); 
        save("./tmp/CairoMakie_015.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QEKAVYPDQMHLRPUO
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//016.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_016.png", output); 
        save("./tmp/CairoMakie_016.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MRYHKTXFQTPIBBLU
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//017.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_017.png", output); 
        save("./tmp/CairoMakie_017.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LOVJORFLESGFQOGJ
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//018.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_018.png", output); 
        save("./tmp/CairoMakie_018.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EMKNURDCUNBGFPWJ
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//019.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_019.png", output); 
        save("./tmp/CairoMakie_019.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module AJJKNFCEAHQTEMLG
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//020.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_020.png", output); 
        save("./tmp/CairoMakie_020.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module CRKOVKCVRQYKZRXT
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//021.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_021.png", output); 
        save("./tmp/CairoMakie_021.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module TTBKVRTNLWMVBUZJ
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//022.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_022.png", output); 
        save("./tmp/CairoMakie_022.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MDXCLNTKBOGVGYMV
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//023.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_023.png", output); 
        save("./tmp/CairoMakie_023.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LIMBDSLHGEQMARRO
    try
        using CairoMakie; CairoMakie.activate!(); 
output = include("./snippets/makie//025.jl")
    display(output);
    try 
        save("./tmp/CairoMakie_025.png", output); 
        save("./tmp/CairoMakie_025.svg", output);
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end





module LHZLCNPCGRHGFLWC
    try
        using Plots; gr(); 
output = include("./snippets/plots//001.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_001.png"); 
        savefig(output, "./tmp/gr_001.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module WOZNATTZPFRUTKHR
    try
        using Plots; gr(); 
output = include("./snippets/plots//002.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_002.png"); 
        savefig(output, "./tmp/gr_002.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module CKEMBOJNDIJWENSX
    try
        using Plots; gr(); 
output = include("./snippets/plots//003.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_003.png"); 
        savefig(output, "./tmp/gr_003.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IWPJOALYQNZTZYPS
    try
        using Plots; gr(); 
output = include("./snippets/plots//004.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_004.png"); 
        savefig(output, "./tmp/gr_004.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DGZXBOREQTXIOWYN
    try
        using Plots; gr(); 
output = include("./snippets/plots//005.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_005.png"); 
        savefig(output, "./tmp/gr_005.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DAFSBEQSTBEYJNTQ
    try
        using Plots; gr(); 
output = include("./snippets/plots//006.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_006.png"); 
        savefig(output, "./tmp/gr_006.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module NQJSQAFJFCTWRLKM
    try
        using Plots; gr(); 
output = include("./snippets/plots//007.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_007.png"); 
        savefig(output, "./tmp/gr_007.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module IBHKBAXSVIAATMGD
    try
        using Plots; gr(); 
output = include("./snippets/plots//008.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_008.png"); 
        savefig(output, "./tmp/gr_008.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module OUCEZJRCUYPXGAEW
    try
        using Plots; gr(); 
output = include("./snippets/plots//009.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_009.png"); 
        savefig(output, "./tmp/gr_009.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module KALDMAXMEUGUJIZZ
    try
        using Plots; gr(); 
output = include("./snippets/plots//010.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_010.png"); 
        savefig(output, "./tmp/gr_010.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MYPBJCSADHWIRLZZ
    try
        using Plots; gr(); 
output = include("./snippets/plots//011.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_011.png"); 
        savefig(output, "./tmp/gr_011.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RFKUFIRCJNRFAOFW
    try
        using Plots; gr(); 
output = include("./snippets/plots//012.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_012.png"); 
        savefig(output, "./tmp/gr_012.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SKHXMMIUYJPNVGZJ
    try
        using Plots; gr(); 
output = include("./snippets/plots//013.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_013.png"); 
        savefig(output, "./tmp/gr_013.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module GUNKYBILNHYZMQDK
    try
        using Plots; gr(); 
output = include("./snippets/plots//014.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_014.png"); 
        savefig(output, "./tmp/gr_014.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module UOVCLLNRJZHBLNYD
    try
        using Plots; gr(); 
output = include("./snippets/plots//015.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_015.png"); 
        savefig(output, "./tmp/gr_015.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DMGNLJXXUVCTOLWC
    try
        using Plots; gr(); 
output = include("./snippets/plots//016.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_016.png"); 
        savefig(output, "./tmp/gr_016.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module WHDNFFNGMGOVERVY
    try
        using Plots; gr(); 
output = include("./snippets/plots//017.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_017.png"); 
        savefig(output, "./tmp/gr_017.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DMBROQQXNUPKYVNB
    try
        using Plots; gr(); 
output = include("./snippets/plots//018.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_018.png"); 
        savefig(output, "./tmp/gr_018.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module MOADLJMSKTUGSLRB
    try
        using Plots; gr(); 
output = include("./snippets/plots//019.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_019.png"); 
        savefig(output, "./tmp/gr_019.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SXRMNNKTXGWAPAJN
    try
        using Plots; gr(); 
output = include("./snippets/plots//020.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_020.png"); 
        savefig(output, "./tmp/gr_020.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module XVVLOELAFMPOPWCD
    try
        using Plots; gr(); 
output = include("./snippets/plots//021.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_021.png"); 
        savefig(output, "./tmp/gr_021.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module KOWOYVLCYHFQOIOS
    try
        using Plots; gr(); 
output = include("./snippets/plots//022.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_022.png"); 
        savefig(output, "./tmp/gr_022.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module KZCQDFNVGAZUIHUQ
    try
        using Plots; gr(); 
output = include("./snippets/plots//023.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_023.png"); 
        savefig(output, "./tmp/gr_023.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module OXWMFPPGYQAOIGSX
    try
        using Plots; gr(); 
output = include("./snippets/plots//024.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_024.png"); 
        savefig(output, "./tmp/gr_024.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module WTZPPEMLHFSGSBDT
    try
        using Plots; gr(); 
output = include("./snippets/plots//025.jl")
    display(output);
    try 
        savefig(output, "./tmp/gr_025.png"); 
        savefig(output, "./tmp/gr_025.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PEJKEEJODYRMPFIQ
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//001.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_001.png"); 
        savefig(output, "./tmp/pgfplotsx_001.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module HCENPCBBWHUEIJJP
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//002.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_002.png"); 
        savefig(output, "./tmp/pgfplotsx_002.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module XHIYZGGSDDMMWZUN
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//003.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_003.png"); 
        savefig(output, "./tmp/pgfplotsx_003.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QEBOWQLJJUSSBSXF
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//004.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_004.png"); 
        savefig(output, "./tmp/pgfplotsx_004.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module PWIUBFRVYLNNOSNF
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//005.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_005.png"); 
        savefig(output, "./tmp/pgfplotsx_005.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module WBBMUXWZHCOQBESR
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//006.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_006.png"); 
        savefig(output, "./tmp/pgfplotsx_006.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module KNDKWHEYXQWTOOFE
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//007.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_007.png"); 
        savefig(output, "./tmp/pgfplotsx_007.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module EWWIFARFAABVIOXI
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//008.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_008.png"); 
        savefig(output, "./tmp/pgfplotsx_008.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module DNWHLVUNXDMJDMSY
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//009.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_009.png"); 
        savefig(output, "./tmp/pgfplotsx_009.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ULXIHWYVHTYWADJV
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//010.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_010.png"); 
        savefig(output, "./tmp/pgfplotsx_010.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module QWPOCDNKXWRZHBWR
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//011.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_011.png"); 
        savefig(output, "./tmp/pgfplotsx_011.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module UCUYCDBZDJSADPOB
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//012.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_012.png"); 
        savefig(output, "./tmp/pgfplotsx_012.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module INYMTHFJTKPCLHHA
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//013.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_013.png"); 
        savefig(output, "./tmp/pgfplotsx_013.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module THFAIMZYSDFNLHWP
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//014.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_014.png"); 
        savefig(output, "./tmp/pgfplotsx_014.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module FQNDDXWXLXOHZRUL
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//015.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_015.png"); 
        savefig(output, "./tmp/pgfplotsx_015.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module XNYKRKDOZKNLWLWR
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//016.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_016.png"); 
        savefig(output, "./tmp/pgfplotsx_016.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module RWDRAWIFAXUVYMEL
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//017.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_017.png"); 
        savefig(output, "./tmp/pgfplotsx_017.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module LRDNMCEKHYHAEYMB
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//018.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_018.png"); 
        savefig(output, "./tmp/pgfplotsx_018.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module SPIMYKGEEHCLZAAV
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//019.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_019.png"); 
        savefig(output, "./tmp/pgfplotsx_019.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module BGCMZHIRDBQLVVIB
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//020.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_020.png"); 
        savefig(output, "./tmp/pgfplotsx_020.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module VDCDJBWUIXNYYWKL
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//021.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_021.png"); 
        savefig(output, "./tmp/pgfplotsx_021.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ZCPJFHONERRTXTJL
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//022.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_022.png"); 
        savefig(output, "./tmp/pgfplotsx_022.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module YFLLQYNYTFZIPXMI
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//023.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_023.png"); 
        savefig(output, "./tmp/pgfplotsx_023.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module TUYGWGXULIDDVTEL
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//024.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_024.png"); 
        savefig(output, "./tmp/pgfplotsx_024.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end


;

module ZXCAAQHEQBKQYAQP
    try
        using Plots; pgfplotsx(); 
output = include("./snippets/plots//025.jl")
    display(output);
    try 
        savefig(output, "./tmp/pgfplotsx_025.png"); 
        savefig(output, "./tmp/pgfplotsx_025.svg");
    catch e
        @warn e
    end


    catch error
        @warn error
    end
end



